# Generated by Django 2.0.2 on 2020-03-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(blank=True, default='DEFAULT VALUE', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
